### ISSUE TITLE
google浏览器左边有滚动条

### ISSUE THREAD

**Issue by naturalwill** [DawnLightning/SASView#1]
google浏览器左边有滚动条
![2016-01-26 14-14-17](https://cloud.githubusercontent.com/assets/9474899/12573738/a698888c-c437-11e5-9050-63159751490e.png)

**Comment by myloverhxx** [comment]
因为你上面书签栏

**Comment by naturalwill** [comment]
建议向左箭头的收起图标独占一行，其他图标可以2列或者多列
